version: '3.4'

services:
  rpgapi:
    image: ${DOCKER_REGISTRY-}rpgapi
    build:
      context: .
      dockerfile: RpgApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - game-network
    depends_on:
      game.database:
        condition: service_healthy
  game.database:
    container_name: "game.database" # host url for my postgres db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - game-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  game-network:
    driver: bridge
